Repository habx/config-ci-front, pull requests merged in 2021-02, with the labels that each got.

#55 APP-18940: Regen lock
  package-lock.json
  package.json
Labels: habx-autorelease

#58 Syncing dev with v0.4.1
  package-lock.json
  package.json
Labels: habx-automerge

#71 APP-19059: Replace exports with require
  storybook/preview.js
  storybook/style.js
Labels: habx-automerge, habx-autorelease

#73 APP-18677: Update TypeScript configuration
  .dependabot/config.yml
  typescript/client.json
  typescript/default.json
Labels: habx-autorelease
