Repository habx/config-ci-front, pull requests merged in 2021-06, with the labels that each got.

#124 APP-21838: Add jsdom env in jest config
  jest/config.js
Labels: autorelease

#125 APP-21908: Exclude android browser from browserslist
  browserslist.js
Labels: automerge, autorelease

#130 APP-22076: Add maxWorkers config
  jest/config.js
Labels: autorelease

#136 APP-22188: chore(CI): Easier CI
  .circleci/config.yml
  package.json
Labels: automerge

#132 APP-22083: Update peer deps
  package.json
Labels: autorelease, autoupdate

#140 APP-22288: Relax ranges of peer dependencies
  package-lock.json
  package.json
Labels: autorelease
