Repository habx/config-ci-front, pull requests merged in 2022-01, with the labels that each got.

#238 APP-26221: Migrate from `create-react-app` to `Vite`
  package-lock.json
  package.json
  typescript/client.json
  vite/client.js
  webpack/overrides.js
  webpack/webpack.config.js
Labels: autorelease-major

#239 APP-26221: Fix resolution of paths when extending configurations
  typescript/client.json
  vite/client.mjs
Labels: automerge, autorelease

#240 Syncing dev with v1.0.1
  typescript/client.json
  vite/client.mjs
Labels: automerge

#241 APP-26221: Fix Cypress TypeScript target
  typescript/cypress.json
Labels: automerge, autorelease

#242 Syncing dev with v1.0.2
  typescript/cypress.json
Labels: automerge

#243 APP-26546: Add vite-plugin-checker plugin
  package-lock.json
  package.json
  vite/client.mjs
Labels: autorelease

#247 APP-26749: Use ESM for storybook
  storybook/preview.js
  storybook/preview.jsx
  storybook/style.jsx
Labels: automerge, autorelease
